export const typesEmoji = {
  fire: "🔥",
  flying: "🦋",
  grass: "🌿",
  poison: "☠️",
  normal: "🐻",
  bug: "🐞",
  water: "💧",
  psychic: "🧠",
  ice: "❄️",
  electric: "⚡",
  dragon: "🐉",
  dark: "🌑",
  fairy: "🧚‍♀️",
  ground: "🏜️",
  rock: " 🪨",
  steel: "🛡️",
  ghost: "👻",
  fighting: "👊",
};
